correction done

diff --git a/GatewayComponents/Utilities/Dockerfile b/GatewayComponents/Utilities/Dockerfile
--- a/GatewayComponents/Utilities/Dockerfile
+++ b/GatewayComponents/Utilities/Dockerfile
@@ -7,6 +7,9 @@ COPY . .
 
 # RUN source /home/app/shra/bin/activate
 RUN pip install -r requirements.txt
-HEALTHCHECK --interval=30s --timeout=30s --start-period=5s --retries=3 CMD curl -f http://localhost:8001/err || exit 1
+RUN apk update && \
+    apk add curl \
+    rm -rf /var/cache/apk/*
+#HEALTHCHECK --interval=30s --timeout=30s --start-period=5s --retries=3 CMD curl -f http://localhost:8001/err || exit 1
 
 CMD ["python", "<app_name>.py"]
